//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spwin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Student
    {
        public int StuID { get; set; }

        [Required(ErrorMessage = "User name is not entered!" )]
        [Display(Name = "User Name")]

        public string UserName { get; set; }

        [Required(ErrorMessage = "Password is not entered!")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [Required(ErrorMessage = "Password is not re-entered!")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password",ErrorMessage ="Password is not match!")]
        [NotMapped]
        public string RePassword { get; set; }

        [Display(Name = "Birthday")]
        public Nullable<System.DateTime> Birthday { get; set; }

        [Display(Name = "Registered Date")]
        public Nullable<System.DateTime> RegDay { get; set; }

        [Display(Name = "A/L Stream")]
        public string Stream { get; set; }
    }
}
